name: investigation-influence-industry
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.11
- pandas
- matplotlib
- jupyter
- python-dotenv
- pip
- moviepy
- pip:
  - TikTokApi
  - playwright
  - tiktok-hashtag-analysis
  - deep-translator
  - yt_dlp
  - urllib3
  - awscli
  - botocore
  - boto3
  - opencv-python

